### PR TITLE
Black borders

### PR DESCRIPTION
**Pull request by ShivRaiGithub**
Added black borders to checkboxes to increase visibility.

### CODE REVIEW

**Review by Morphclue — CHANGES_REQUESTED** [review]
Thanks for your contribution!

Some general information: Basic CSS-Styling should be done in the `.scss`-files next to components and not in html. Furthermore we use the Bootstrap-framework in our project, which provides a utility class for borders: `border border-dark` which can be also used in our `html`-files. It would probably make sense to style all `app-check-button`s in [this file](https://github.com/Morphclue/apollusia/blob/18559a5a0e34432c683fa0a1164ba2e3d71c5cd4/apps/frontend/src/app/poll/check-button/check-button.component.html#L12).

Lastly, make sure that the change also makes check-boxes more readable in darkmode, since I don't think that it helps with readability if we just change it to black borders:
Pre-change:
image
Post-change:
image

**Comment by ShivRaiGithub** [comment]
How about I use french-violet (#7b2cbfff) ? In my opinion it will work on both light and dark mode while going along with the theme of the app.

**Comment by Morphclue** [comment]
In my opinion `french-violet` doesn't increase readability. It creates too much visual distraction in my opinion. Furthermore this should be done with Bootstrap utility classes. In our case since `french-violet` is declared as a primary color (see: [style.scss](https://github.com/Morphclue/apollusia/blob/master/apps/frontend/src/styles.scss)) you can also use `border border-primary`.

@ShivRaiGithub Can you attach screenshots to your changes, so I don't have to checkout it locally first?
@Clashsoft any thoughts on adding borders for our checkboxes or coloring them?

**Comment by Clashsoft** [comment]
I don't see the benefit in this change. Is there a real visibility problem with these checkboxes? Did you check accessibility guidelines regarding contrast etc.? If so, please let us know.

**Pull request closed without merging**
